# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71810bb253812eeed4f06aa941443ba1b118680e2d8d1254e8176a1306d99dbf6a49b263c8a51a2edce0828b9e95b97865c5f48158092ee4d3f22c37f8b935ab
  devise_secret_key: 721b8fc80b271e04611ec119deeb495bd910c67146d0a6b91d2ef27a0602b0ba8b945fd7aa56b817e81543a9dd27d67212290aee2dbd387fffce222467756c68
  admin_login: admin@admin.com
  admin_password: admin123456

test:
  secret_key_base: f9ac77cebc421fca836e20e3e0f4e14fec055a830018bfca8c602a987a7bd073f4618652deee01a54cf7f50ff04ee6f1540a521b87336547b2bb4e2c10d130d1
  devise_secret_key: 721b8fc80b271e04611ec119deeb495bd910c67146d0a6b91d2ef27a0602b0ba8b945fd7aa56b817e81543a9dd27d67212290aee2dbd387fffce222467756c68
  admin_login: admin@admin.com
  admin_password: admin123456

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_TOKEN"] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>
  admin_login: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWD"] %>
